//CONVENCIONES PARA EVITAR ERRORES
const URL = "http://localhost:3001/";
const GET_USER = "GET_USER";
const POST_USER = "POST_USER";
const LOGIN_USER = "LOGIN_USER";
const LOGIN_ATTEMPT = "LOGIN_ATTEMPT";
const LOGOUT_USER = "LOGOUT_USER";
const UPDATE_PROVINCE = "UPDATE_PROVINCE";
const UPDATE_DISTRICT = "UPDATE_DISTRICT";
const UPDATE_FIELDS = "UPDATE_FIELDS";
const UPDATE_INFO = "UPDATE_INFO";
const UPDATE_FIELD_RESERVATIONS = "UPDATE_FIELD_RESERVATIONS";
const UPDATE_RESERVATION_DATA = "UPDATE_RESERVATION_DATA";
const SET_DISTRICT = "SET_DISTRICT";
const SET_PROVINCE = "SET_PROVINCE";
const LOCATION_API = "";
const GET_FIELDS = "GET_FIELDS";
const GET_INFO = "GET_INFO";
const GET_FIELD_TYPE = " GET_FIELD_TYPE";
const POST_COMPLEX = "POST_COMPLEX";
const RESERVATION_MP = "RESERVATION_MP";
const POST_FIELD = "POST_FIELD";
const UPDATE_FIELD = "UPDATE_FIELD";
const ORDER_BY_PRICE = "ORDER_BY_PRICE";
const FILTER_BY_TYPE = "FILTER_BY_TYPE";
const POST_RESERVATION = "POST_RESERVATION";
const FILTER_BY_PROVINCE = "FILTER_BY_PROVINCE";
const FILTER_BY_DISTRICT = "FILTER_BY_DISTRICT";
const GET_COMPLEX_INFO = "GET_COMPLEX_INFO";
const FILTER_BY_LOC = "FILTER_BY_LOC";
const RESET_LOCATION = "RESET_LOCATION";
const ARG_API_FLAG = "ARG_API_FLAG";
const G_REGISTRATION = "G_REGISTRATION";
const LOGOUT_G = "LOGOUT_G";
const GET_COMPLEX_ALL = "GET_COMPLEX_ALL";
const UPDATE_USER = "UPDATE_USER";
const DELETE_USER = "DELETE_USER";
const DELETE_RESERVATION = "DELETE_RESERVATION";
const UPDATE_COMPLEX = "UPDATE_COMPLEX";
const DELETE_COMPLEX = "DELETE_COMPLEX";
const DELETE_FIELD = "DELETE_FIELD";
const FAIL_MAIL = "FAIL_MAIL";
const ACTIVE_SESSION_GOOGLE = "ACTIVE_SESSION_GOOGLE";
const GET_BY_NAME = "GET_BY_NAME";
const GET_USER_ALL = "GET_USER_ALL";
const GET_FIELDS_BY_COMPLEX = 'GET_FIELDS_BY_COMPLEX';
const FILTER_COMPLEX_BY_DISTRICT = "FFILTER_COMPLEX_BY_DISTRICT";
const FILTER_COMPLEX_BY_PROVINCE = "FILTER_COMPLEX_BY_PROVINCE";
const POST_REVIEW = "POST_REVIEW";
const GET_REVIEWS = "GET_REVIEWS";
const UPDATE_OWNER_COMPLEXES = "UPDATE_OWNER_COMPLEXES";
const USER_MESSAGE = "USER_MESSAGE";
const GET_FIELD_BY_NAME = "GET_FIELD_BY_NAME";



module.exports = {
  GET_USER,
  LOCATION_API,
  UPDATE_PROVINCE,
  UPDATE_DISTRICT,
  UPDATE_FIELDS,
  UPDATE_FIELD,
  UPDATE_FIELD_RESERVATIONS,
  UPDATE_OWNER_COMPLEXES,
  UPDATE_RESERVATION_DATA,
  UPDATE_INFO,
  SET_PROVINCE,
  SET_DISTRICT,
  POST_USER,
  LOGIN_USER,
  LOGIN_ATTEMPT,
  LOGOUT_USER,
  GET_FIELDS,
  GET_INFO,
  GET_FIELD_TYPE,
  POST_COMPLEX,
  RESERVATION_MP,
  POST_FIELD,
  ORDER_BY_PRICE,
  FILTER_BY_TYPE,
  POST_RESERVATION,
  FILTER_BY_PROVINCE,
  FILTER_BY_DISTRICT,
  GET_COMPLEX_INFO,
  FILTER_BY_LOC,
  URL,
  RESET_LOCATION,
  ARG_API_FLAG,
  G_REGISTRATION,
  LOGOUT_G,
  GET_COMPLEX_ALL,
  UPDATE_USER,
  DELETE_USER,
  DELETE_RESERVATION,
  UPDATE_COMPLEX,
  DELETE_COMPLEX,
  DELETE_FIELD,
  FAIL_MAIL,
  ACTIVE_SESSION_GOOGLE,
  GET_BY_NAME,
  GET_USER_ALL,
  GET_FIELDS_BY_COMPLEX,
  FILTER_COMPLEX_BY_DISTRICT,
  FILTER_COMPLEX_BY_PROVINCE,
  POST_REVIEW,
  GET_REVIEWS,
  USER_MESSAGE,
  GET_FIELD_BY_NAME
};